import { useEffect, useState } from 'react'
import './App.css'

const stages = [
  { name: 'Starter', ko: '알아차리기', desc: '현재 학생의 수행을 알아차리게 하는 단계', role: '학생의 시도와 수행 근거를 구체적으로 짚어 줍니다.', talk: '관찰한 사실을 두 가지 기준으로 나누어 기록했구나.', when: '학생이 자신의 현재 수행을 먼저 인식해야 할 때', caution: '막연한 칭찬이나 수준 판단으로 들리지 않게 합니다.', examples: ['두 자료에서 공통점을 먼저 찾아 표시했구나.', '실험 결과를 예상과 실제로 나누어 기록했네.', '문단마다 중심이 되는 낱말에 표시했구나.'] },
  { name: 'Planner', ko: '목표와 연결하기', desc: '이미 해낸 점과 학습 목표를 연결하는 단계', role: '성취한 부분과 다음 목표 사이의 거리를 분명히 합니다.', talk: '변인을 한 가지로 정한 점은 정확해. 공정한 실험을 위해 무엇을 같게 해야 할까?', when: '학생의 강점을 바탕으로 다음 목표를 세울 때', caution: '교사가 목표를 모두 정하기보다 학생의 선택을 남겨 둡니다.', examples: ['근거를 한 가지 찾았어. 주장을 더 분명하게 할 근거를 하나 더 골라 볼까?', '계산 방법은 알맞아. 풀이를 친구가 이해하게 설명하려면 무엇을 덧붙이면 좋을까?', '지역의 특징을 찾았어. 이 특징이 생활 모습과 어떻게 연결되는지 살펴보자.'] },
  { name: 'Guide', ko: '단서 제공하기', desc: '다음 수행을 위한 구체적인 단서를 주는 단계', role: '학생이 다시 수행할 수 있을 만큼의 단서만 제공합니다.', talk: '결과가 달라진 까닭을 찾으려면, 두 실험에서 달랐던 조건을 하나씩 비교해 볼까?', when: '방향은 알지만 다음 행동을 시작하기 어려울 때', caution: '정답이나 완성된 문장을 대신 주지 않습니다.', examples: ['첫 문장과 마지막 문장에서 반복되는 낱말을 찾아볼까?', '수직선에서 0과의 거리를 먼저 확인해 보자.', '지도 범례에서 같은 색이 무엇을 뜻하는지 살펴볼까?'] },
  { name: 'Coach', ko: '스스로 점검하기', desc: '학생이 스스로 점검하고 수정하도록 질문하는 단계', role: '비교·점검 질문으로 학생의 자기 수정을 이끕니다.', talk: '네가 세운 예상과 실험 결과를 비교하면, 설명을 고쳐야 할 부분이 어디일까?', when: '학생이 기준을 활용해 스스로 수정할 수 있을 때', caution: '답을 유도하는 닫힌 질문만 이어 가지 않습니다.', examples: ['이 근거가 네 주장을 가장 잘 뒷받침하는지 어떻게 확인할 수 있을까?', '두 풀이 중 오류를 더 쉽게 찾을 수 있는 방법은 무엇일까?', '친구 의견을 듣고 네 생각에서 바꾸고 싶은 부분이 있니?'] },
  { name: 'Designer', ko: '새롭게 확장하기', desc: '배운 내용을 새로운 상황으로 확장하는 단계', role: '전이할 맥락을 열고 학생이 새 과제를 설계하게 합니다.', talk: '이번 실험에서 찾은 관계를 교실의 다른 현상에도 적용해 설명해 볼래?', when: '배움을 새로운 문제나 맥락에 적용할 준비가 되었을 때', caution: '단계가 높다는 이유만으로 모든 학생에게 요구하지 않습니다.', examples: ['다른 독자를 위한 글이라면 표현을 어떻게 바꾸겠니?', '같은 원리를 활용한 새로운 문제를 만들어 볼래?', '우리 지역의 문제에 적용할 조사 계획을 세워 볼까?'] },
]

const tools = [
  ['one', '원마커', '학생의 현재 이해 정도나 선택을 빠르게 표시하게 하는 도구', '전체 학생의 반응을 짧은 시간에 확인할 때', '현재 상태 확인'],
  ['hand', '다섯손가락', '자기 이해 정도를 손가락 수로 간단히 표현하는 자기점검 도구', '설명이나 활동 직후 이해 정도를 점검할 때', '자기 점검'],
  ['ticket', '입·퇴장 티켓', '수업 전후에 짧게 이해 정도나 배움을 확인하는 기록 도구', '수업 시작 전 선개념이나 마무리 배움을 확인할 때', '진단과 회고'],
  ['check', '체크리스트', '수행 요소의 충족 여부를 빠르게 확인하는 도구', '여러 수행 기준을 빠짐없이 확인할 때', '과정 점검'],
  ['document', '자기점검표', '학생이 자신의 수행을 스스로 돌아보게 하는 도구', '과제 제출 전 기준에 따라 스스로 검토할 때', '자기 조절'],
  ['compare', '예시 비교', '좋은 예와 수정이 필요한 예를 비교하며 기준을 이해하도록 돕는 도구', '평가 기준을 구체적인 사례로 이해시킬 때', '기준 이해'],
  ['speech', '다시 말하기', '학생이 자신의 생각이나 답을 다시 표현하며 점검하게 하는 도구', '생각은 있으나 표현이 불명확할 때', '재수행'],
  ['people', '동료 설명', '친구에게 설명하며 이해를 정리하고 확인하는 도구', '말로 설명하며 개념을 정교화할 때', '상호 피드백'],
  ['oral', '즉시 구두 피드백', '활동 중 바로 짧게 말로 제공하는 피드백', '즉시 수정할 수 있는 수행 장면에서', '즉각적 교정'],
  ['comment', '디지털 코멘트', '디지털 플랫폼에서 개별 의견이나 조언을 남기는 피드백 방식', '결과물에 개별 기록을 남기고 다시 확인할 때', '기록형 피드백'],
]

function Icon({ type }) {
  const common = { fill: 'none', stroke: 'currentColor', strokeWidth: 1.8, strokeLinecap: 'round', strokeLinejoin: 'round' }
  const shapes = {
    one: <><circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/></>,
    hand: <path d="M7 12V7a1.5 1.5 0 0 1 3 0v3-5a1.5 1.5 0 0 1 3 0v5-4a1.5 1.5 0 0 1 3 0v5-2a1.5 1.5 0 0 1 3 0v5c0 5-3 7-7 7-3 0-5-2-7-5l-2-3a1.5 1.5 0 0 1 2-2l2 1Z"/>,
    ticket: <path d="M4 7h16v3a2 2 0 0 0 0 4v3H4v-3a2 2 0 0 0 0-4V7Zm8 0v10"/>,
    check: <><rect x="4" y="4" width="16" height="16" rx="2"/><path d="m8 12 3 3 6-7"/></>,
    document: <><path d="M6 3h9l3 3v15H6V3Z"/><path d="M14 3v4h4m-8 7 2 2 4-5"/></>,
    compare: <><rect x="3" y="6" width="8" height="12" rx="1"/><rect x="13" y="6" width="8" height="12" rx="1"/><path d="M6 10h2m8 0h2"/></>,
    speech: <path d="M4 5h16v11H9l-4 3v-3H4V5Zm4 5h8"/>,
    people: <><circle cx="8" cy="8" r="2"/><circle cx="16" cy="8" r="2"/><path d="M3 18c0-3 2-5 5-5s5 2 5 5m-1-3c1-2 5-3 8 0"/></>,
    oral: <><circle cx="8" cy="10" r="3"/><path d="M3 20c0-4 2-6 5-6s5 2 5 6m1-14h7v8h-3l-2 2v-2h-2V6Z"/></>,
    comment: <><rect x="4" y="4" width="16" height="14" rx="2"/><path d="m8 21 4-3h5M8 9h8m-8 4h5"/></>,
  }
  return <svg viewBox="0 0 24 24" aria-hidden="true" {...common}>{shapes[type]}</svg>
}

function Header({ goHome, openHelp }) {
  return <header className="header"><button className="brand" onClick={goHome}>Feed<span>ON</span></button><div className="quick-help" aria-label="빠른 도움"><button onClick={() => openHelp('tools')} aria-label="피드백 도구 도움말"><Icon type="check"/><span>피드백 도구</span></button><button onClick={() => openHelp('stages')} aria-label="피드백 5단계 도움말"><span className="steps-icon">5</span><span>피드백 5단계</span></button></div></header>
}

function Modal({ type, close }) {
  useEffect(() => { const f = e => e.key === 'Escape' && close(); document.addEventListener('keydown', f); return () => document.removeEventListener('keydown', f) }, [close])
  return <div className="overlay" onMouseDown={e => e.target === e.currentTarget && close()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><div><p className="eyebrow">QUICK REFERENCE</p><h2 id="modal-title">FeedON 피드백 {type === 'tools' ? '도구' : '5단계'}</h2></div><button className="close" onClick={close} aria-label="닫기">×</button></div>{type === 'tools' ? <div className="tool-grid">{tools.map(t => <ToolCard key={t[1]} tool={t} detailed />)}</div> : <><p className="modal-intro">학생의 현재 수행을 확인하는 것에서 시작해 스스로 점검하고 새로운 상황으로 확장하도록 피드백의 깊이를 조절합니다.</p><div className="stage-guide">{stages.map((s, i) => <article key={s.name}><span className="stage-no">0{i + 1}</span><div><div className="stage-title"><h3>{s.name}</h3><span>{s.ko}</span><InfoTip text={s.desc}/></div><p><b>교사의 역할</b> {s.role}</p><blockquote>“{s.talk}”</blockquote></div></article>)}</div><div className="notice"><b>단계는 학생의 수준표가 아닙니다.</b><p>같은 학생에게도 상황에 따라 다른 단계의 피드백을 사용할 수 있습니다. 단계가 높을수록 항상 더 좋은 것이 아니라, 학생에게 필요한 지원 정도에 따라 적절한 단계를 선택합니다.</p></div></>}</section></div>
}

function InfoTip({ text }) { const [on, setOn] = useState(false); return <span className="info-wrap"><button className="info" onClick={() => setOn(!on)} aria-label={text} aria-expanded={on}>i</button><span className={`tooltip ${on ? 'show' : ''}`} role="tooltip">{text}</span></span> }
function ToolCard({ tool: t, detailed = false }) { return <article className="tool-card"><div className="tool-line"><span className="tool-icon"><Icon type={t[0]}/></span><div><h3>{t[1]}</h3>{!detailed && <p>{t[4]}</p>}</div><InfoTip text={t[2]}/></div>{detailed && <><p>{t[2]}</p><dl><div><dt>활용 시점</dt><dd>{t[3]}</dd></div><div><dt>피드백 목적</dt><dd>{t[4]}</dd></div></dl></>}</article> }

function Home({ navigate, openHelp }) {
  return <main className="home"><section className="hero-section"><p className="eyebrow">TEACHING & FEEDBACK DESIGN</p><h1>평가에서 피드백까지,<br/><em>학생의 다음 성장</em>을 설계합니다.</h1><p className="lead">교육과정과 수업의 흐름을 연결하고, 학생의 실제 수행에서 다음 배움을 발견하는 교사용 설계 도구</p><div className="track-grid"><button className="track assessment" onClick={() => navigate('assessment')}><span className="track-num">01</span><span><b>평가 ON</b><small>수업·평가 계획하기</small></span><i>→</i></button><button className="track feedback" onClick={() => navigate('feedback')}><span className="track-num">02</span><span><b>피드백 ON</b><small>학생 피드백 만들기</small></span><i>→</i></button></div><button className="text-button" onClick={() => openHelp('stages')}><span className="steps-icon">5</span> 피드백 5단계 알아보기 <span>→</span></button></section><section className="home-note"><span>FeedON의 설계 원칙</span><p>결과를 판정하는 데서 멈추지 않고, 관찰한 수행을 학생의 다음 행동으로 연결합니다.</p></section></main>
}

const initialAssessment = { grade: '', subject: '', unit: '', sessions: '4', focus: [] }
function Field({ label, required, children, hint }) { return <label className="field"><span>{label}{required && <i>필수</i>}</span>{children}{hint && <small>{hint}</small>}</label> }
function PageIntro({ step, title, desc }) { return <div className="page-intro"><span className="step">{step}</span><div><h1>{title}</h1><p>{desc}</p></div></div> }

function AssessmentForm({ initial, onSubmit, back }) {
  const [form, setForm] = useState(initial || initialAssessment); const focuses = ['개념 이해','탐구','의사소통','문제 해결','실생활 적용','협력','기타']
  const set = (k,v) => setForm({...form,[k]:v}); const submit=e=>{e.preventDefault();onSubmit(form)}
  return <main className="page"><button className="back" onClick={back}>← 처음으로</button><PageIntro step="평가 ON · 1/2" title="수업의 맥락을 알려주세요" desc="입력한 내용으로 탐구의 흐름과 관찰 가능한 평가를 설계합니다."/><form className="form-sheet" onSubmit={submit}><div className="form-grid"><Field label="학년" required><select value={form.grade} onChange={e=>set('grade',e.target.value)} required><option value="">선택하세요</option>{[1,2,3,4,5,6].map(n=><option key={n}>{n}학년</option>)}</select></Field><Field label="과목" required><select value={form.subject} onChange={e=>set('subject',e.target.value)} required><option value="">선택하세요</option>{['국어','수학','사회','과학','도덕','체육','음악','미술','실과','영어'].map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="단원" required hint="예: 우리 지역의 모습과 생활"><input value={form.unit} onChange={e=>set('unit',e.target.value)} required placeholder="단원명 또는 핵심 내용을 입력하세요"/></Field><Field label="예상 차시 수"><input type="number" min="1" max="12" value={form.sessions} onChange={e=>set('sessions',e.target.value)}/></Field><fieldset><legend>강조하고 싶은 학습 <span>선택</span></legend><div className="chips">{focuses.map(x=><label key={x} className={form.focus.includes(x)?'selected':''}><input type="checkbox" checked={form.focus.includes(x)} onChange={()=>set('focus', form.focus.includes(x)?form.focus.filter(y=>y!==x):[...form.focus,x])}/>{x}</label>)}</div></fieldset><div className="form-actions"><button type="button" className="secondary" onClick={back}>취소</button><button className="primary">평가 설계안 만들기 <span>→</span></button></div></form></main>
}

function makeAssessment(form) { const n=Math.min(Number(form.sessions)||4,6); return { standard:'확인 필요', area:`${form.subject}과 관련 영역`, note:'2022 개정 교육과정 원문에서 학년군과 단원에 해당하는 성취기준을 확인한 뒤 교사가 최종 선택해 주세요.', unitQuestions:['우리 지역의 자연환경은 사람들의 생활 모습에 어떤 영향을 줄까?','더 살기 좋은 지역을 만들기 위해 우리는 무엇을 살펴보아야 할까?'], sessions:Array.from({length:n},(_,i)=>({focus:['경험 떠올리기','자료에서 특징 찾기','관계 설명하기','관점 비교하기','생각 정리하기','삶에 적용하기'][i]||'배움 확장하기',q:`${i+1}차시의 배움을 우리 생활과 어떻게 연결해 설명할 수 있을까?`})), elements:['글의 중심 생각을 뒷받침하는 내용을 찾아 근거와 함께 설명한다.','읽는 사람과 목적을 고려해 알맞은 표현을 선택한다.','친구의 의견을 듣고 자신의 표현을 구체적으로 수정한다.'], task:{name:'우리 반을 위한 문제 해결 설명서',situation:'생활 속 문제를 수학적 방법으로 해결하고 풀이 과정을 친구에게 소개합니다.',perform:'해결 전략을 두 가지 이상 시도하고, 선택한 방법과 결과가 타당한 까닭을 설명합니다.',link:'문제 해결 과정, 수학적 의사소통, 결과의 타당성을 함께 관찰합니다.'}, method:'교사 관찰평가 + 수행평가',methodWhy:'실제 수행 과정에서 전략을 선택하고 설명을 수정하는 모습을 관찰하며, 완성된 결과물과 해결 과정의 근거를 함께 확인하기에 적절합니다.',tool:'관찰 체크리스트 + 수행 기록지'} }

function Section({ no, title, children }) { return <section className="result-section"><div className="section-heading"><span>{no}</span><h2>{title}</h2></div>{children}</section> }
function AssessmentResult({ form, result, toFeedback, edit }) { return <main className="page result-page"><button className="back" onClick={edit}>← 입력 내용 수정</button><PageIntro step="평가 ON · 2/2" title={`${form.grade} ${form.subject} 평가 설계안`} desc={`${form.unit} · ${form.sessions}차시${form.focus.length?' · '+form.focus.join(', '):''}`}/><div className="result-doc"><Section no="01" title="교육과정 연결"><div className="standard"><span className="status">확인 필요</span><div><h3>관련 성취기준 코드와 문구</h3><p>신뢰할 수 있는 교육과정 원문 확인이 필요합니다.</p></div></div><dl className="info-rows"><div><dt>관련 영역 후보</dt><dd>{result.area}</dd></div><div><dt>적용 시 고려사항</dt><dd>{result.note}</dd></div></dl></Section><Section no="02" title="탐구 설계"><h3 className="subhead">단원 탐구질문 제안 <small>사회 예시</small></h3><ol className="big-questions">{result.unitQuestions.map(q=><li key={q}>{q}</li>)}</ol><h3 className="subhead">차시별 탐구질문</h3><div className="session-table">{result.sessions.map((s,i)=><div key={i}><b>{i+1}차시</b><span>{s.focus}</span><p>{s.q}</p></div>)}</div></Section><Section no="03" title="평가 설계"><h3 className="subhead">평가 요소 <small>국어 예시</small></h3><ul className="check-list">{result.elements.map(x=><li key={x}>{x}</li>)}</ul><h3 className="subhead">평가 과제 <small>수학 예시</small></h3><div className="task-block"><h3>{result.task.name}</h3><dl className="info-rows"><div><dt>평가 상황</dt><dd>{result.task.situation}</dd></div><div><dt>학생 수행</dt><dd>{result.task.perform}</dd></div><div><dt>평가 요소와 연결</dt><dd>{result.task.link}</dd></div></dl></div><div className="recommend-pair"><div><span>추천 평가 방법</span><h3>{result.method}</h3><p>{result.methodWhy}</p></div><div><span>추천 평가 도구</span><h3>{result.tool}</h3><p>관찰 기준과 학생의 설명을 구분해 기록하면 수행의 변화가 선명해집니다.</p></div></div></Section><Section no="04" title="FeedON 성장 단계"><p className="section-desc">국가교육과정의 공식 성취수준 명칭이 아닌, 피드백 설계를 위한 FeedON의 관찰 언어입니다.</p><div className="growth"><div><b>확장</b><p>새로운 상황에 적용하거나 배움을 확장할 수 있어요.</p></div><div><b>성장</b><p>핵심을 대체로 달성했고 일부 보완으로 안정될 수 있어요.</p></div><div><b>도움</b><p>예시, 단서, 질문, 모델링 등의 지원이 필요해요.</p></div></div></Section></div><button className="primary bridge" onClick={toFeedback}>이 평가로 학생 피드백 만들기 <span>→</span></button></main> }

const blankFeedback={grade:'',subject:'',unit:'',session:'',goal:'',observation:'',level:'잘 모르겠음'}
function FeedbackForm({ initial, onSubmit, back }) { const [f,setF]=useState({...blankFeedback,...initial});const set=(k,v)=>setF({...f,[k]:v});return <main className="page"><button className="back" onClick={back}>← 이전 화면</button><PageIntro step="피드백 ON · 1/2" title="학생의 수행을 들려주세요" desc="판단보다 관찰한 말과 행동을 구체적으로 적을수록 다음 행동이 선명해집니다."/>{initial?.fromAssessment&&<div className="linked"><span>평가 ON에서 연결됨</span><b>{f.grade} · {f.subject} · {f.unit}</b><p>평가 설계 정보가 자동으로 채워졌습니다. 학생 수행만 추가해 주세요.</p></div>}<form className="form-sheet" onSubmit={e=>{e.preventDefault();onSubmit(f)}}><div className="form-grid"><Field label="학년" required><select value={f.grade} onChange={e=>set('grade',e.target.value)} required><option value="">선택</option>{[1,2,3,4,5,6].map(n=><option key={n}>{n}학년</option>)}</select></Field><Field label="과목" required><select value={f.subject} onChange={e=>set('subject',e.target.value)} required><option value="">선택</option>{['국어','수학','사회','과학','도덕','체육','음악','미술','실과','영어'].map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="단원" required><input value={f.unit} onChange={e=>set('unit',e.target.value)} required placeholder="단원명"/></Field><div className="form-grid"><Field label="차시"><input value={f.session} onChange={e=>set('session',e.target.value)} placeholder="예: 3차시"/></Field><Field label="평가 요소 또는 학습 목표" required><input value={f.goal} onChange={e=>set('goal',e.target.value)} required placeholder="관찰하려는 수행"/></Field></div><Field label="학생이 보인 실제 수행 모습" required hint="과학 예시: 예상은 정확히 말했지만, 실험 결과를 기록할 때 측정 단위를 두 번 빠뜨렸다. 모둠 친구의 기록을 보고 스스로 한 곳을 고쳤다."><textarea rows="7" value={f.observation} onChange={e=>set('observation',e.target.value)} required placeholder="평가 과정에서 학생이 말하거나 행동한 모습, 오류, 해결 과정, 친구와의 상호작용 등을 구체적으로 입력하세요."/></Field><fieldset><legend>현재 수행 수준 <span>선택</span></legend><div className="radio-row">{['확장','성장','도움','잘 모르겠음'].map(x=><label key={x} className={f.level===x?'selected':''}><input type="radio" name="level" checked={f.level===x} onChange={()=>set('level',x)}/>{x}</label>)}</div>{f.level==='잘 모르겠음'&&<p className="field-note">관찰 기록을 바탕으로 가까운 단계를 제안합니다. 최종 판단은 교사가 합니다.</p>}</fieldset><div className="form-actions"><button type="button" className="secondary" onClick={back}>취소</button><button className="primary">피드백 설계안 만들기 <span>→</span></button></div></form></main> }

function FeedbackResult({ data, edit }) { const [open,setOpen]=useState([]);const level=data.level==='잘 모르겠음'?'성장':data.level;return <main className="page result-page"><button className="back" onClick={edit}>← 수행 기록 수정</button><PageIntro step="피드백 ON · 2/2" title="학생의 다음 행동을 위한 피드백" desc={`${data.grade} ${data.subject} · ${data.unit}`}/>{data.level==='잘 모르겠음'&&<div className="level-suggest"><span>수행 수준 제안</span><p>현재 관찰 기록을 기준으로 <b>‘성장’ 단계</b>에 가까워 보입니다.</p><small>자동 제안은 참고용이며 최종 판단은 교사가 합니다.</small></div>}<div className="result-doc"><Section no="01" title="피드백 전략"><div className="strategy"><div><span>추천 피드백 방식</span><h3>질문형 피드백</h3></div><p>학생이 수행의 일부를 이미 해냈으므로 정답을 바로 제시하기보다, 자신의 기록과 기준을 비교해 스스로 빠진 부분을 찾고 수정하도록 질문하는 것이 적절합니다.</p></div><div className="evidence"><b>관찰 근거</b><p>“{data.observation}”</p><span>교사가 선택한 단계 · {level}</span></div></Section><Section no="02" title="추천 피드백 도구"><p className="section-desc">도구 위에 마우스를 올리거나 정보 버튼을 눌러 활용법을 확인하세요.</p><div className="recommended-tools">{[tools[4],tools[5],tools[6]].map(t=><ToolCard key={t[1]} tool={t}/>)}</div></Section><Section no="03" title="5단계 Teacher Talk"><p className="section-desc">같은 수행 증거를 바탕으로 지원의 깊이를 달리한 문장입니다. 학생의 필요에 맞는 단계를 골라 사용하세요.</p><div className="talk-list">{stages.map((s,i)=>{const isOpen=open.includes(i);return <article key={s.name} className={isOpen?'open':''}><div className="talk-top"><span>0{i+1}</span><div><h3>{s.name} <small>{s.ko}</small></h3><blockquote>“{s.talk}”</blockquote></div></div><button className="expand" onClick={()=>setOpen(isOpen?open.filter(x=>x!==i):[...open,i])} aria-expanded={isOpen}>{isOpen?'접기':'예시 더보기'} <span>{isOpen?'−':'+'}</span></button>{isOpen&&<div className="talk-detail"><dl><div><dt>단계의 목적</dt><dd>{s.desc}</dd></div><div><dt>사용 시점</dt><dd>{s.when}</dd></div><div><dt>교사가 주의할 점</dt><dd>{s.caution}</dd></div></dl><h4>다른 Teacher Talk 예시</h4><ul>{s.examples.map(x=><li key={x}>“{x}”</li>)}</ul></div>}</article>})}</div></Section></div></main> }

function App() {
  const [page,setPage]=useState('home'),[help,setHelp]=useState(null),[aForm,setAForm]=useState(null),[aResult,setAResult]=useState(null),[fForm,setFForm]=useState(null),[fResult,setFResult]=useState(null)
  const assessmentDone=f=>{setAForm(f);setAResult(makeAssessment(f));setPage('assessmentResult');scrollTo(0,0)}
  const connect=()=>{setFForm({grade:aForm.grade,subject:aForm.subject,unit:aForm.unit,session:`${aForm.sessions}차시`,goal:aResult.elements[0],fromAssessment:true});setPage('feedback');scrollTo(0,0)}
  const feedbackDone=f=>{setFForm(f);setFResult(f);setPage('feedbackResult');scrollTo(0,0)}
  const nav=p=>{setPage(p);scrollTo(0,0)}
  return <><Header goHome={()=>nav('home')} openHelp={setHelp}/>{page==='home'&&<Home navigate={nav} openHelp={setHelp}/>} {page==='assessment'&&<AssessmentForm initial={aForm} onSubmit={assessmentDone} back={()=>nav('home')}/>} {page==='assessmentResult'&&<AssessmentResult form={aForm} result={aResult} edit={()=>nav('assessment')} toFeedback={connect}/>} {page==='feedback'&&<FeedbackForm initial={fForm} onSubmit={feedbackDone} back={()=>nav(aResult?'assessmentResult':'home')}/>} {page==='feedbackResult'&&<FeedbackResult data={fResult} edit={()=>nav('feedback')}/>} {help&&<Modal type={help} close={()=>setHelp(null)}/>}<footer><b>FeedON</b><span>학생 주도성을 켜는 퍼스널 평가·피드백 도우미</span></footer></>
}

export default App
